#!/usr/bin/env python3

import os
import sys
import rclpy
import subprocess

from geometry_msgs.msg import PointStamped
from rclpy.qos import QoSProfile
from rclpy.node import Node
from rclpy.executors import ExternalShutdownException

class PingPublisher(Node):
    def __init__(self):
        super().__init__('ping_publisher')
        qos = QoSProfile(depth=10)

        # Declare parameters
        self.declare_parameter('max_pub_hz', 50)
        self.declare_parameter('deadline_msec', 500)

        # Get parameters
        max_freq = self.get_parameter('max_pub_hz').get_parameter_value().integer_value
        self.deadline = self.get_parameter('deadline_msec').get_parameter_value().integer_value / 1000.0

        self.timer = self.create_timer(1.0 / max_freq, self.timer_callback)
        self.pub = self.create_publisher(PointStamped, 'ping', qos)

    def timer_callback(self):
        result = subprocess.run(
            ['ping', '-6', '-c', '1', '-W', str(self.deadline), 'turtlebot'],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        if result.returncode == 0:
            output = result.stdout
            time_ms = float(output.split('time=')[1].split(' ms')[0])
        else:
            time_ms = float('Inf')

        msg = PointStamped()
        msg.header.frame_id = 'base_link'
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.point.z = time_ms
        self.pub.publish(msg)
        # self.get_logger().info(f'Published ping time: {time_ms} ms')

def main():
    try:
        rclpy.init()
        node = PingPublisher()
        rclpy.spin(node)
    except (KeyboardInterrupt, ExternalShutdownException):
        pass

if __name__ == '__main__':
    main()
